version: '3'
services: 
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
        - '3000:3000'
    volumes:
        - /home/frontend/node_modules
        - .:/home/frontend
